-- MySQL Script generated by MySQL Workbench
-- Wed Feb 14 16:51:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Brunata` DEFAULT CHARACTER SET utf8 ;
USE `Brunata` ;

-- -----------------------------------------------------
-- Table `Brunata`.`stan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Brunata`.`stan` ;

CREATE TABLE IF NOT EXISTS `Brunata`.`stan` (
  `idstan` INT(6) NOT NULL,
  `vlasnik_ime` VARCHAR(45) NULL,
  `vlasnik_prezime` VARCHAR(45) NULL,
  `ulaz` INT(2) NOT NULL,
  `sprat` VARCHAR(8) NOT NULL,
  `broj_stana` VARCHAR(2) NOT NULL,
  `kvadratura` INT(3) NOT NULL,
  `tip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Brunata`.`racun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Brunata`.`racun` ;

CREATE TABLE IF NOT EXISTS `Brunata`.`racun` (
  `idracun` INT NOT NULL,
  `period` DATE NOT NULL,
  `ukupna_kvadratura` FLOAT(5,2) NOT NULL,
  `ukupno_imp` INT(5) NOT NULL,
  `ukupno_kWh` FLOAT(5,2) NOT NULL,
  `ukupn0_kWh_po_m2` FLOAT(5,2) NOT NULL,
  `ukupn0_kWh_po_imp` FLOAT(5,2) NOT NULL,
  PRIMARY KEY (`idracun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Brunata`.`ocitani_impulsi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Brunata`.`ocitani_impulsi` ;

CREATE TABLE IF NOT EXISTS `Brunata`.`ocitani_impulsi` (
  `idstan` INT(6) NOT NULL,
  `idracun` INT NOT NULL,
  `br_impulsa` INT(5) NOT NULL,
  `stan_kWh_po_m2` FLOAT(5,2) NOT NULL,
  `stan_kWh_po_imp` FLOAT(5,2) NOT NULL,
  `stan_kWh` FLOAT(5,2) NOT NULL,
  INDEX `racun_idx` (`idracun` ASC),
  INDEX `idstan_idx` (`idstan` ASC),
  CONSTRAINT `racun`
    FOREIGN KEY (`idracun`)
    REFERENCES `Brunata`.`racun` (`idracun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idstan`
    FOREIGN KEY (`idstan`)
    REFERENCES `mydb`.`stan` (`idstan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


DESCRIBE ocitani_impulsi;

