-- MySQL Script generated by MySQL Workbench
-- Thu Feb 15 20:11:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema brunata
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema brunata
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `brunata` DEFAULT CHARACTER SET utf8 ;
USE `brunata` ;

-- -----------------------------------------------------
-- Table `brunata`.`2016_01`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `brunata`.`2016_01` ;

-- CREATE TABLE IF NOT EXISTS `brunata`.`2016_01` (
--   `Sprat` VARCHAR(9) NULL DEFAULT NULL,
--   `Impulsi` VARCHAR(13) NULL DEFAULT NULL,
--   `Var potrosnja` VARCHAR(20) NULL DEFAULT NULL,
--   `Stanar` VARCHAR(23) NULL DEFAULT NULL,
--   `Broj stana` VARCHAR(10) NULL DEFAULT NULL,
--   `Ukupna potrosnja` VARCHAR(16) NULL DEFAULT NULL,
--   `Ulaz` VARCHAR(21) NULL DEFAULT NULL,
--   `Kvadratura` VARCHAR(10) NULL DEFAULT NULL,
--   `Zajedn potrosnja` VARCHAR(20) NULL DEFAULT NULL,
--   `Kod stana` VARCHAR(9) NOT NULL,
--   PRIMARY KEY (`Kod stana`),
--   UNIQUE INDEX `Kod stana` (`Kod stana` ASC))
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8;


-- -- -----------------------------------------------------
-- -- Table `brunata`.`2016_02`
-- -- -----------------------------------------------------
-- DROP TABLE IF EXISTS `brunata`.`2016_02` ;

-- CREATE TABLE IF NOT EXISTS `brunata`.`2016_02` (
--   `Sprat` VARCHAR(9) NULL DEFAULT NULL,
--   `Impulsi` VARCHAR(13) NULL DEFAULT NULL,
--   `Var potrosnja` VARCHAR(20) NULL DEFAULT NULL,
--   `Stanar` VARCHAR(23) NULL DEFAULT NULL,
--   `Broj stana` VARCHAR(10) NULL DEFAULT NULL,
--   `Ukupna potrosnja` VARCHAR(16) NULL DEFAULT NULL,
--   `Ulaz` VARCHAR(21) NULL DEFAULT NULL,
--   `Kvadratura` VARCHAR(10) NULL DEFAULT NULL,
--   `Zajedn potrosnja` VARCHAR(20) NULL DEFAULT NULL,
--   `Kod stana` VARCHAR(9) NULL DEFAULT NULL)
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8;


-- -- -----------------------------------------------------
-- -- Table `brunata`.`2016_03`
-- -- -----------------------------------------------------
-- DROP TABLE IF EXISTS `brunata`.`2016_03` ;

-- CREATE TABLE IF NOT EXISTS `brunata`.`2016_03` (
--   `Sprat` VARCHAR(9) NULL DEFAULT NULL,
--   `Impulsi` VARCHAR(13) NULL DEFAULT NULL,
--   `Var potrosnja` VARCHAR(20) NULL DEFAULT NULL,
--   `Stanar` VARCHAR(23) NULL DEFAULT NULL,
--   `Broj stana` VARCHAR(10) NULL DEFAULT NULL,
--   `Ukupna potrosnja` VARCHAR(16) NULL DEFAULT NULL,
--   `Ulaz` VARCHAR(21) NULL DEFAULT NULL,
--   `Kvadratura` VARCHAR(10) NULL DEFAULT NULL,
--   `Zajedn potrosnja` VARCHAR(18) NULL DEFAULT NULL,
--   `Kod stana` VARCHAR(9) NULL DEFAULT NULL)
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8;


-- -- -----------------------------------------------------
-- -- Table `brunata`.`2016_04`
-- -- -----------------------------------------------------
-- DROP TABLE IF EXISTS `brunata`.`2016_04` ;

-- CREATE TABLE IF NOT EXISTS `brunata`.`2016_04` (
--   `Sprat` VARCHAR(9) NULL DEFAULT NULL,
--   `Impulsi` VARCHAR(13) NULL DEFAULT NULL,
--   `Var potrosnja` VARCHAR(20) NULL DEFAULT NULL,
--   `Stanar` VARCHAR(23) NULL DEFAULT NULL,
--   `Broj stana` VARCHAR(10) NULL DEFAULT NULL,
--   `Ukupna potrosnja` VARCHAR(16) NULL DEFAULT NULL,
--   `Ulaz` VARCHAR(21) NULL DEFAULT NULL,
--   `Kvadratura` VARCHAR(10) NULL DEFAULT NULL,
--   `Zajedn potrosnja` VARCHAR(18) NULL DEFAULT NULL,
--   `Kod stana` VARCHAR(9) NULL DEFAULT NULL)
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8;


-- -- -----------------------------------------------------
-- -- Table `brunata`.`2016_10`
-- -- -----------------------------------------------------
-- DROP TABLE IF EXISTS `brunata`.`2016_10` ;

-- CREATE TABLE IF NOT EXISTS `brunata`.`2016_10` (
--   `Sprat` VARCHAR(9) NULL DEFAULT NULL,
--   `Impulsi` VARCHAR(13) NULL DEFAULT NULL,
--   `Var potrosnja` VARCHAR(20) NULL DEFAULT NULL,
--   `Stanar` VARCHAR(23) NULL DEFAULT NULL,
--   `Broj stana` VARCHAR(10) NULL DEFAULT NULL,
--   `Ukupna potrosnja` VARCHAR(16) NULL DEFAULT NULL,
--   `Ulaz` VARCHAR(21) NULL DEFAULT NULL,
--   `Kvadratura` VARCHAR(10) NULL DEFAULT NULL,
--   `Zajedn potrosnja` VARCHAR(18) NULL DEFAULT NULL,
--   `Kod stana` VARCHAR(9) NULL DEFAULT NULL)
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8;


-- -- -----------------------------------------------------
-- -- Table `brunata`.`2016_11`
-- -- -----------------------------------------------------
-- DROP TABLE IF EXISTS `brunata`.`2016_11` ;

-- CREATE TABLE IF NOT EXISTS `brunata`.`2016_11` (
--   `Sprat` VARCHAR(9) NULL DEFAULT NULL,
--   `Impulsi` VARCHAR(13) NULL DEFAULT NULL,
--   `Var potrosnja` VARCHAR(20) NULL DEFAULT NULL,
--   `Stanar` VARCHAR(23) NULL DEFAULT NULL,
--   `Broj stana` VARCHAR(10) NULL DEFAULT NULL,
--   `Ukupna potrosnja` VARCHAR(16) NULL DEFAULT NULL,
--   `Ulaz` VARCHAR(21) NULL DEFAULT NULL,
--   `Kvadratura` VARCHAR(10) NULL DEFAULT NULL,
--   `Zajedn potrosnja` VARCHAR(20) NULL DEFAULT NULL,
--   `Kod stana` VARCHAR(9) NULL DEFAULT NULL)
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8;


-- -- -----------------------------------------------------
-- -- Table `brunata`.`2016_12`
-- -- -----------------------------------------------------
-- DROP TABLE IF EXISTS `brunata`.`2016_12` ;

-- CREATE TABLE IF NOT EXISTS `brunata`.`2016_12` (
--   `Sprat` VARCHAR(9) NULL DEFAULT NULL,
--   `Impulsi` VARCHAR(13) NULL DEFAULT NULL,
--   `Var potrosnja` VARCHAR(21) NULL DEFAULT NULL,
--   `Stanar` VARCHAR(23) NULL DEFAULT NULL,
--   `Broj stana` VARCHAR(10) NULL DEFAULT NULL,
--   `Ukupna potrosnja` VARCHAR(16) NULL DEFAULT NULL,
--   `Ulaz` VARCHAR(21) NULL DEFAULT NULL,
--   `Kvadratura` VARCHAR(10) NULL DEFAULT NULL,
--   `Zajedn potrosnja` VARCHAR(20) NULL DEFAULT NULL,
--   `Kod stana` VARCHAR(9) NULL DEFAULT NULL)
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8;


-- -- -----------------------------------------------------
-- -- Table `brunata`.`2017_01`
-- -- -----------------------------------------------------
-- DROP TABLE IF EXISTS `brunata`.`2017_01` ;

-- CREATE TABLE IF NOT EXISTS `brunata`.`2017_01` (
--   `Sprat` VARCHAR(9) NULL DEFAULT NULL,
--   `Impulsi` VARCHAR(13) NULL DEFAULT NULL,
--   `Var potrosnja` VARCHAR(22) NULL DEFAULT NULL,
--   `Stanar` VARCHAR(23) NULL DEFAULT NULL,
--   `Broj stana` VARCHAR(10) NULL DEFAULT NULL,
--   `Ukupna potrosnja` VARCHAR(16) NULL DEFAULT NULL,
--   `Ulaz` VARCHAR(21) NULL DEFAULT NULL,
--   `Kvadratura` VARCHAR(10) NULL DEFAULT NULL,
--   `Zajedn potrosnja` VARCHAR(19) NULL DEFAULT NULL,
--   `Kod stana` VARCHAR(9) NULL DEFAULT NULL)
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8;


-- -- -----------------------------------------------------
-- -- Table `brunata`.`2017_02`
-- -- -----------------------------------------------------
-- DROP TABLE IF EXISTS `brunata`.`2017_02` ;

-- CREATE TABLE IF NOT EXISTS `brunata`.`2017_02` (
--   `Sprat` VARCHAR(9) NULL DEFAULT NULL,
--   `Impulsi` VARCHAR(13) NULL DEFAULT NULL,
--   `Var potrosnja` VARCHAR(20) NULL DEFAULT NULL,
--   `Stanar` VARCHAR(23) NULL DEFAULT NULL,
--   `Broj stana` VARCHAR(10) NULL DEFAULT NULL,
--   `Ukupna potrosnja` VARCHAR(16) NULL DEFAULT NULL,
--   `Ulaz` VARCHAR(21) NULL DEFAULT NULL,
--   `Kvadratura` VARCHAR(10) NULL DEFAULT NULL,
--   `Zajedn potrosnja` VARCHAR(20) NULL DEFAULT NULL,
--   `Kod stana` VARCHAR(9) NULL DEFAULT NULL)
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8;


-- -- -----------------------------------------------------
-- -- Table `brunata`.`2017_03`
-- -- -----------------------------------------------------
-- DROP TABLE IF EXISTS `brunata`.`2017_03` ;

-- CREATE TABLE IF NOT EXISTS `brunata`.`2017_03` (
--   `Sprat` VARCHAR(9) NULL DEFAULT NULL,
--   `Impulsi` VARCHAR(13) NULL DEFAULT NULL,
--   `Var potrosnja` VARCHAR(20) NULL DEFAULT NULL,
--   `Stanar` VARCHAR(23) NULL DEFAULT NULL,
--   `Broj stana` VARCHAR(10) NULL DEFAULT NULL,
--   `Ukupna potrosnja` VARCHAR(16) NULL DEFAULT NULL,
--   `Ulaz` VARCHAR(21) NULL DEFAULT NULL,
--   `Kvadratura` VARCHAR(10) NULL DEFAULT NULL,
--   `Zajedn potrosnja` VARCHAR(18) NULL DEFAULT NULL,
--   `Kod stana` VARCHAR(9) NULL DEFAULT NULL)
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8;


-- -- -----------------------------------------------------
-- -- Table `brunata`.`2017_04`
-- -- -----------------------------------------------------
-- DROP TABLE IF EXISTS `brunata`.`2017_04` ;

-- CREATE TABLE IF NOT EXISTS `brunata`.`2017_04` (
--   `Sprat` VARCHAR(9) NULL DEFAULT NULL,
--   `Impulsi` VARCHAR(13) NULL DEFAULT NULL,
--   `Var potrosnja` VARCHAR(20) NULL DEFAULT NULL,
--   `Stanar` VARCHAR(23) NULL DEFAULT NULL,
--   `Broj stana` VARCHAR(10) NULL DEFAULT NULL,
--   `Ukupna potrosnja` VARCHAR(16) NULL DEFAULT NULL,
--   `Ulaz` VARCHAR(21) NULL DEFAULT NULL,
--   `Kvadratura` VARCHAR(10) NULL DEFAULT NULL,
--   `Zajedn potrosnja` VARCHAR(18) NULL DEFAULT NULL,
--   `Kod stana` VARCHAR(9) NULL DEFAULT NULL)
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8;


-- -- -----------------------------------------------------
-- -- Table `brunata`.`2017_10`
-- -- -----------------------------------------------------
-- DROP TABLE IF EXISTS `brunata`.`2017_10` ;

-- CREATE TABLE IF NOT EXISTS `brunata`.`2017_10` (
--   `id` INT(6) NOT NULL,
--   `Vlasnik_st` VARCHAR(23) NULL DEFAULT NULL,
--   `Ulaz` VARCHAR(6) NULL DEFAULT NULL,
--   `Sprat` VARCHAR(9) NULL DEFAULT NULL,
--   `Br_stana` VARCHAR(8) NULL DEFAULT NULL,
--   `Tip` VARCHAR(5) NULL DEFAULT NULL,
--   `m2` DECIMAL(4,2) NULL DEFAULT NULL,
--   `Impulsi` INT(7) NULL DEFAULT NULL,
--   `kWh_VAR_TOTAL` VARCHAR(13) NULL DEFAULT NULL,
--   `kWh_Var` VARCHAR(7) NULL DEFAULT NULL,
--   `Var_posto_Stan` VARCHAR(14) NULL DEFAULT NULL,
--   `kWh_m2_TOTAL` VARCHAR(12) NULL DEFAULT NULL,
--   `kWh_m2` VARCHAR(6) NULL DEFAULT NULL,
--   `m2_posto_Stan` VARCHAR(13) NULL DEFAULT NULL,
--   `kWhSum` VARCHAR(6) NULL DEFAULT NULL,
--   `posto_SUM` VARCHAR(9) NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   UNIQUE INDEX `id` (`id` ASC))
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `brunata`.`stan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brunata`.`stan` ;

CREATE TABLE IF NOT EXISTS `brunata`.`stan` (
  `idstan_stari` INT(6) NULL DEFAULT NULL,
  `idstan_novi` INT(6) NOT NULL,
  `vlasnik` VARCHAR(100) NULL DEFAULT NULL,
  `ulaz` VARCHAR(12) NOT NULL,
  `sprat` ENUM('Prizemlje', 'I', 'II', 'III', 'IV', 'V') NOT NULL,
  `broj_stana` VARCHAR(3) NOT NULL,
  `kvadratura` FLOAT(10,2) NOT NULL,
  `tip` ENUM('Stan', 'Lokal') NOT NULL,
  PRIMARY KEY (`idstan_novi`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `brunata`.`racun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brunata`.`racun` ;

CREATE TABLE IF NOT EXISTS `brunata`.`racun` (
  `idracun` INT(11) NOT NULL,
  `period` DATE NOT NULL,
  `ukupna_kvadratura` FLOAT(10,2) NOT NULL,
  `ukupno_imp` INT(5) NOT NULL,
  `ukupno_kWh` FLOAT(10,2) NOT NULL,
  `ukupno_kWh_po_m2` FLOAT(10,2) NOT NULL,
  `ukupno_kWh_po_imp` FLOAT(10,2) NOT NULL,
  PRIMARY KEY (`idracun`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `brunata`.`ocitani_impulsi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brunata`.`ocitani_impulsi` ;

CREATE TABLE IF NOT EXISTS `brunata`.`ocitani_impulsi` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idstan` INT(11) NOT NULL,
  `idracun` INT(11) NOT NULL,
  `br_impulsa` INT(5) NOT NULL,
  `stan_kWh_po_m2` FLOAT(10,2) NOT NULL,
  `stan_kWh_po_imp` FLOAT(10,2) NOT NULL,
  `stan_kWh` FLOAT(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `racun` (`idstan` ASC, `idracun` ASC),
  INDEX `racun_idx` (`idracun` ASC),
  INDEX `idstan_idx` (`idstan` ASC),
  CONSTRAINT `idstan`
    FOREIGN KEY (`idstan`)
    REFERENCES `brunata`.`stan` (`idstan_novi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `racun`
    FOREIGN KEY (`idracun`)
    REFERENCES `brunata`.`racun` (`idracun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 382
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
